### ISSUE TITLE
Header won't Show on Woocommerce Shop Page on Elmentor 2.0

### ISSUE THREAD

**Issue by Flipback8** [Nikschavan/header-footer-elementor#100]
Header won't Show on Woocommerce Shop Page on Elmentor 2.0

**Comment by Nikschavan** [comment]
Can you give a URL of the page @Flipback8 ?

**Comment by Flipback8** [comment]
https://bookthetech.com/shop


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Nikhil <notifications@github.com> Date: 4/7/18  12:33 AM  (GMT-05:00) To: Nikschavan/header-footer-elementor <header-footer-elementor@noreply.github.com> Cc: Flipback8 <Flipback8@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Nikschavan/header-footer-elementor] Header won't Show on
  Woocommerce Shop Page on Elmentor 2.0 (#100) 
Can you give a URL of the page @Flipback8 ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Nikschavan/header-footer-elementor","title":"Nikschavan/header-footer-elementor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Nikschavan/header-footer-elementor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Nikschavan in #100: Can you give a URL of the page @Flipback8 ?"}],"action":{"name":"View Issue","url":"https://github.com/Nikschavan/header-footer-elementor/issues/100#issuecomment-379431524"}}}

**Comment by Nikschavan** [comment]
you have the javascript error on your shop page ([screenshot](https://cl.ly/qjIr)) and that is breaking the appear animation on the page.

You should contact Elementor support regarding the JS error as this is coming from their JS files.
