### ISSUE TITLE
Header NavMenu Active Background color

### ISSUE THREAD

**Issue by diversityreporting** [Nikschavan/header-footer-elementor#105]
Currently you can only set the active background color to be on the Primary Navigation Bar, but not the sub menu.

Is there a plan to allow users to view which sub-menu they're on with a different active background color?

**Comment by Nikschavan** [comment]
@diversityreporting Are you using any Elementor menu module plugin?
This plugin does not add the navigation menu addon. The menu module is coming from some third party addon that you must have installed on your site.

You will have to contact their support in order to get this feature implemented.
