### ISSUE TITLE
Sticky Header Problem

### ISSUE THREAD

**Issue by tjp3rd** [Nikschavan/header-footer-elementor#106]
I have an issue with making the header sticky in elementor. I have used multiple compatible themes with same issue. When you make the header sticky it causes the entire page to start scolling slowly up after you start scrolling down the page and you are not able to click on any website functions. When you first land on the page it is stable but once you start scrolling it just keeps going by itself till it gets to the bottom of the page. When you turn off the sticky feature the page works fine.

**Comment by tjp3rd** [comment]
Hellooooo, is there anybody out there?

**Comment by besweeet** [comment]
How are you implementing the sticky feature? For my theme, I added the following CSS to the header and have no issues.
```
position: fixed;
width: 100%;
z-index: 999;
```

**Comment by tjp3rd** [comment]
Thanks for getting back with me.  It's still doing the same thing. I am
implementing the sticky feature on the advanced tab under scrolling effect
with elementor. It is a header with a logo, navigation menu, and a search
bar.

**Comment by besweeet** [comment]
How did you apply that CSS? I found the specific CSS classes and applied them in the theme's customizer (Page Builder Framework). In my case:

```
.elementor-322 .elementor-element.elementor-element-142d82f {
    position: fixed;
    width: 100%;
    z-index: 99999;
}
```

**Comment by tjp3rd** [comment]
I really appreciate the help. Adding the code in combination with another
thing I did fixed the issue. From the layout section for the header in
elementor I had to also make sure content width was set to full width not
boxed. This combination fixed the scrolling issue.

Thanks

**Comment by Nikschavan** [comment]
Hello Guys, This issue is coming from Elementor's Sticky JS.

At this point, it seems that this is already fixed by Elementor in an update.
