### ISSUE TITLE
Adding Header Footer Elementor support for your theme

### ISSUE THREAD

**Issue by jodeyf** [Nikschavan/header-footer-elementor#115]
Can you assist with this ulr

www.fcmarine.co.uk

steps on how to complete this process

**Comment by Nikschavan** [comment]
You are using a theme that is not by default supported.

1. You can contact the theme developer to add support to your theme. Here is a tutorial that you can send them to - https://github.com/Nikschavan/header-footer-elementor/wiki/Adding-Header-Footer-Elementor-support-for-your-theme
2. You can add support for this plugin from a child theme. Here is a step by step tutorial for this - https://github.com/Nikschavan/header-footer-elementor/wiki/Add-support-to-Header-Footer-Elementor-from-the-Child-Theme
