### ISSUE TITLE
Appearance -> Header Footer Builder

### ISSUE THREAD

**Issue by johnnyd85252** [Nikschavan/header-footer-elementor#116]
Downloaded plugin and activated it. It shows in the installed plugins as active. However, it is not showing under "appearance". Please advise.

**Comment by Nikschavan** [comment]
Which theme are you using? Is this one of the supported themes? - https://github.com/Nikschavan/header-footer-elementor#which-themes-are-supported-by-this-plugin

**Comment by johnnyd85252** [comment]
Genesis. I had to download and activate three elementor plugins to view header/footer in appearance. Too many plugins to achieve what I believe is a simple issue. After deactivating the plugins and deleting them, I found freewebheaders.com and created and installed the header into my site in less than ten minutes. Thanks anyway.


________________________________

**Comment by misha17-27** [comment]
can you help me.i want to ask .Why is this shown?If you look at the big screen, the footer rises.I use this plugin Header Footer Elementor.This is my test site https://testme.pp.ua/tb1/ru/nashi-uslugi/
http://joxi.ru/Dr8R8KzC4Jqgl2
http://joxi.ru/J2bg7edsXgnNDA

**Comment by misha17-27** [comment]
![conco - google chrome](https://user-images.githubusercontent.com/36574768/42904393-02bd6872-8ae6-11e8-84d3-16b5666f9013.jpg)
![conco - google chrome2](https://user-images.githubusercontent.com/36574768/42904395-02e12a50-8ae6-11e8-96ee-65ddb5c9b516.jpg)

**Comment by Nikschavan** [comment]
@misha17-27 Looks like you have already ficed the problem on your site.
For anyone else looking for solution to force footer to stay at the bottom, This snippet will work for you - https://gist.github.com/Nikschavan/2f11e28ffd806f72f805a8af3a8f6f03
