### ISSUE TITLE
WP Custom Header Nav Widget doesn't work

### ISSUE THREAD

**Issue by freakstyleart** [Nikschavan/header-footer-elementor#117]
Hi guys, 

I've been using your header-footer plugin for over a year now, and it's been working fantastic. However, recentely, the links that I've provided with the Custom Header Nav Widget no longer work. They're custom links using the anchor widget. 

Funny thing is that they work fine on my product page, but on my home page, instead of moving to the assigned anchor, clicking on a link will just move you to the top of the page. 

I'm not sure if this is an issue with your plugin, or an issue with the widget itself. I've checked to see if the sticky header plugin has anything to do with it, but deactivating that solves nothing. Since I'm not exactly a pro at making websites, I thought I'd contact you to ask what might be wrong.

![creating menus](https://user-images.githubusercontent.com/40885787/42369896-932e0644-810b-11e8-8917-d46cc6f1f814.jpg)
![menu_manage_locations](https://user-images.githubusercontent.com/40885787/42369897-935b49ba-810b-11e8-98e6-11d136092097.jpg)
![using_plugin](https://user-images.githubusercontent.com/40885787/42369898-938a373e-810b-11e8-8182-cdadaff9be2b.jpg)

Thanks in advance,
Frederieke

**Comment by Nikschavan** [comment]
This sounds like some scrolling JS is interfering with the menu links on your site. This plugin does not add any JS which can do this. This should be coming from some different plugin.

This video tutorial will help you find the exact cause for this problem - https://www.youtube.com/watch?v=E1F2v4ab09E
