### ISSUE TITLE
Support for Polylang (multilanguage)

### ISSUE THREAD

**Issue by pgpalafox** [Nikschavan/header-footer-elementor#119]
Hello,

First of all, to say that your plugin is fantastic and works very well ... but I have a problem with the multilanguage.

I use Polylang (version 2.3.8), 'Header Footer Elementor' (version 1.0.15) and Elementor Pro (version 2.0.16), in a site with WordPress 4.9.7. Polylang works very well (in this moment I use two languages, Spanish and English), but with the 'Header Footer Elementor' plugin I can not find the option to have two footers and two headers and how to show one or the other depending on what language in the web client is selected, the Spanish or the English.

Please, is there any way to do it? Another way? I need translate my header and footer.

Very thanks in advance,

**Comment by pgpalafox** [comment]
Hello,

Please, not any news about this issue? 

Thanks in advance,

**Comment by Nikschavan** [comment]
Hey HFE already works correctly with polylang. You just have to enable post type in polylang's settings. See screenshot - https://cl.ly/3I390R0X1Y0z
