### ISSUE TITLE
Hide the footer of a page on Ocean WP

### ISSUE THREAD

**Issue by Lndbe971** [Nikschavan/header-footer-elementor#121]
Hi, 

I am using Elementor with Ocean WP.

I would like to hide the footer of a page of my website. I followed your instruction above by installing the plugin Code Snippets but the footer still visible :
https://github.com/Nikschavan/header-footer-elementor/wiki/How-to-disable-Header-Footer-on-specific-page

Could you give me a solution ?

Regards,

**Comment by Nikschavan** [comment]
@Lndbe971 Can you open up a ticket from https://wpastra.com/support/submit-a-ticket/ for this support query?
