### ISSUE TITLE
Adding Header Footer Elementor support to Primer/Mins

### ISSUE THREAD

**Issue by danielle1179** [Nikschavan/header-footer-elementor#148]
Hello! I'm using the Primer theme and child theme Mins from GoDaddy. I am not sure how to add support for this plugin to my theme files. Can you please help me do so without breaking my site?

http://coolco.samhillmusic.com

Please let me know if you need to log in. Thank you!

**Comment by Nikschavan** [comment]
This will be fixed with v1.2.0 (#207)

@danielle1179 Can you try v1.2.0 which adds support for all the themes - https://share.getcloudapp.com/WnuEdN7m

Your feedback will be very helpful.
