### ISSUE TITLE
loading doesnt finish

### ISSUE THREAD

**Issue by helvetica123** [Nikschavan/header-footer-elementor#164]
i selected header from type of template then i clicked edit with elementor but the elementor logo which says loading doesnt finish.what must i do?

**Comment by helvetica123** [comment]
i click back button on chrome then elementor edit screen came but i cant add element bc element panel - you know it is located left of screen- shows loading

**Comment by Nikschavan** [comment]
I could not reproduce this error. Are you using a supported theme?
Also, can you open up a [support ticket](https://wpastra.com/support/open-a-ticket/) so that we can take a closer look at this?
