### ISSUE TITLE
The preview could not be loaded in Elementor

### ISSUE THREAD

**Issue by outfoxer** [Nikschavan/header-footer-elementor#188]
I see this error while trying to edit header or footer with Elementor https://take.ms/CsrXi “The preview could not be loaded”. The regular paged are edited well.

How can I fix that?

**Comment by Nikschavan** [comment]
Can you open up a [support ticket](https://wpastra.com/support/free-support/) with more information on this?

I tried reproducing this but could not. This will need to be debugged on your website.
