### ISSUE TITLE
Can't "Edit With Elementor"

### ISSUE THREAD

**Issue by reachadam** [Nikschavan/header-footer-elementor#2]
When I create a new header template > Save It > Click Edit With Elementor > the page just refreshes.

**Comment by reachadam** [comment]
Ok so I think there is a conflict with the plugin GP Premium, when I disabled that, it now works.

**Comment by Nikschavan** [comment]
Hello @reachadam Can you check again if there is still incompatibility with this plugin and GP Premium? a lot has been changed in the plugin now.

Also, the plugin slug is also different now so you will have to delete the old version and install this version separately.
