### ISSUE TITLE
disable menu toggle?

### ISSUE THREAD

**Issue by computercheck** [Nikschavan/header-footer-elementor#23]
Hi Nikschavan

Thanks for the great plugin.  Not sure if this is where to ask a question about header footer but:

What's the easiest way to disable the menu toggle for mobile devices and still keep the original menu?  I have a very small secondary menu (using the "default navmenu" element) which I don't want to collapse/toggle on smaller screens.

Thanks

**Comment by Nikschavan** [comment]
Hello @computercheck 

What plugin are you using to create the menu?

**Comment by computercheck** [comment]
header-footer-elementor

**Comment by Nikschavan** [comment]
The header footer elementor plugin just allows you to create header footer using elementor, but this yet does not have a menu module.

Which module are you using to create a menu? Can you give me a link to a site where you are using this?

**Comment by computercheck** [comment]
http://preview.computercheck.com.au/aals/

My apologies, I now realise it is the NavMenu Addon For Elementor that is supplying those elements.

**Comment by computercheck** [comment]
![screen shot 2017-06-09 at 9 38 06 pm](https://user-images.githubusercontent.com/29305510/26978320-b6077a5c-4d5d-11e7-83b8-23fb5b3c93f1.png)
