### ISSUE TITLE
Current page

### ISSUE THREAD

**Issue by gianlucaimprota** [Nikschavan/header-footer-elementor#24]
Hi, I'm using your plug in. I created a custom header in Elementor and I used your plug in to make it appear on my site. Everything was perfect except for the text of the current page, which is bold, while I don't want it to be bold, I want it to be regular. Is there a way to change this?

**Comment by Nikschavan** [comment]
Can you give me a link where I can see this error? @gianlucaimprota

**Comment by gianlucaimprota** [comment]
Unfortunately I'm building my site locally, so I'm not able to send you a link. I can add that I'm also using the NavMenu add-on for Elementor. Could that be the issue?

**Comment by Nikschavan** [comment]
I am thinking this is because some of the modules loaded on the page/header are adding font weight bold and that CSS is being carried forward to all the headings. This will have to be inspected using developer tools in the browser to check which CSS is overriding this font weight.

**Comment by Nikschavan** [comment]
Closing the issue for inactivity, You can still respond here if the problem is not yet solved.
