### ISSUE TITLE
Menu button doesn't show up menu (in responsive design) (v1.3.0)

### ISSUE THREAD

**Issue by lapinos03** [Nikschavan/header-footer-elementor#250]
Hello !
I have a problem with the button that doesn't show the menu when clicked (in responsive design). This happens indifferently in desktop Chrome 80.0.3987.122 or  Edge 44.17763.831.0 or on Android Chrome.
But when the window is resized, then it works !
Could you please have a look at this bug ? 
Thanks !
					

== Theme ==
	Name: Twenty Seventeen
	Version: 2.2
	Author: the WordPress team
	Child Theme: No

== Active Plugins ==
	Elementor
		Version: 2.9.3
		Author: Elementor.com

	Elementor - Header, Footer & Blocks
		Version: 1.3.0
		Author: Brainstorm Force, Nikhil Chavan

	Menu Icons
		Version: 0.12.2
		Author: ThemeIsle

**Comment by lvne** [comment]
Hi I have the same issue regarding that in navigation menu, the first click of the hamburger is working but the next clicks are not working anymore in responsive view

I use the astra theme and elementor plugin

**Comment by SuryawanshiPrajakta** [comment]
Hello!

We have fixed this issue in v1.3.1. Kindly update Elementor-header, Footer & Blocks to the latest version. That will help :)
