### ISSUE TITLE
Double footer

### ISSUE THREAD

**Issue by rickvana** [Nikschavan/header-footer-elementor#255]
Hello,

We just updated our website with plugins and themes, and now we have a double footer. It's not recognised in Elementor and we can't seem to delete it.

Hope you have a fix for this
![footer](https://user-images.githubusercontent.com/61792858/75891905-bbc65580-5e30-11ea-9ba8-8839523716cc.png)

**Comment by vrundakansara** [comment]
Hey @rickvana ,

I tried this scenario with the latest version and it is working as expected without any errors.

Can you try deactivating all the plugins and just keeping Elementor and header-footer-elementor active and see if you still see the issue?

If yet you see the error please raise a request [here](https://uaelementor.com/support/).

Regards,
Vrunda Kansara

**Comment by rickvana** [comment]
Hey Vrunda,

I still keep seeing the issue. The rest of our site is entirely Wordpress, except for the footer. Maybe that is the issue? But even if we delete it it still stays there.

I will also raise an error at the place you directed me.

Thanks for your help and have a nice day.

**Comment by vrundakansara** [comment]
Hey @rickvana ,
Do you still face such an issue? We would like to know more about it and fix it for you.

Regards,
Vrunda Kansara

**Comment by rickvana** [comment]
Hey Vrunda,

The issue is somewhat solved. We managed to get rid of the double footer, it's a bit over the copyright but it's not a major issue anymore.

Thanks for the help and have a nice day.
