### ISSUE TITLE
My theme (BlankSlate) doesn't support HFE and the documentation doesn't explain how to make it to support it

### ISSUE THREAD

**Issue by ghost** [Nikschavan/header-footer-elementor#26]
My theme (BlankSlate) doesn't support HFE and the documentation doesn't explain how to make it to support it.

Can you please update [this documentation](https://github.com/Nikschavan/header-footer-elementor#which-themes-are-supported-by-this-plugin) on what and where to add to BlankSlate's files to make it support in HFE?

Thanks anyway!, Ben,

**Comment by Nikschavan** [comment]
Hello @Benqzq,

**Comment by Benqzq** [comment]
Nikhil, will a mechanism that makes sure HFE headers/footers are **always first** also needed?

**Comment by Nikschavan** [comment]
Can you explain what do you mean by *always first*? ideally, it will not require any extra changes than that.

There will be more changes required from your site when Transparent Header(#9) and Sticky header(#10) are implemented.
