### ISSUE TITLE
Layout error behind Shopping Cart Widget

### ISSUE THREAD

**Issue by cornychaos** [Nikschavan/header-footer-elementor#269]
When Shopping Cart Widget is set to type Custom, the `<div>` block is not closed. All subsequent elements will have the wrong design definitions. (For display:inline)

Specifically, I found the missing `</div>` tag in the class-cart.php at the end. The `<div class=hfe-menu-cart__toggle elementor-wrapper">` tag is not closed. (row 582) 

`</div>` tag missing between rows 592-593.

**Comment by SuryawanshiPrajakta** [comment]
Hello @cornychaos,

Thank you for bringing this to us!

We have fixed this issue with EHF v1.4.1. Please update EHF to the latest version and let us know if you still face any issues.

Regards,
Prajakta Suryawanshi
