### ISSUE TITLE
Fix php-notice in widgets/class-navigation-menu.php

### ISSUE THREAD

**Issue by vollyimnetz** [Nikschavan/header-footer-elementor#286]
### Describe the bug:
Please fix the php notice "Trying to access array offset on value of type null ..." that is thrown in /header-footer-elementor/inc/widgets-manager/widgets/class-navigation-menu.php on line 1835

### To reproduce:
1. Create a header or footer block (or use elementor on any page)
2. add the "HFE Navigation Menü" widget
3. visit your wp-debug.log after visiting the page

### Expected behavior:
A clean log file.

I know its only a notice - but its a junk notice that is add noise to the debug-log on every page-load.

### WordPress version:
5.4.1

### Elementor version:
2.9.8

### Your Plugin version:
1.4.1

**Comment by SuryawanshiPrajakta** [comment]
Hello @vollyimnetz,

Thank you for bringing this to us!

We have fixed this notice with EHF v1.5.0. Please update EHF to the latest version.

Let us know if we can help with anything else.

Have a great day ahead!
