### ISSUE TITLE
Allow using multiple headers / footers.

### ISSUE THREAD

**Issue by Nikschavan** [Nikschavan/header-footer-elementor#29]
Location settings developed for [Astra](https://github.com/brainstormforce/astra) can be used for this.

**Comment by Audelweiss** [comment]
Hello, I'm trying to use this plugin on my WP multisite with Astra theme but I have the following error message
![capture](https://user-images.githubusercontent.com/17007867/32278868-5593fb9c-bf17-11e7-92d5-4882dfd40f24.PNG)

**Comment by Nikschavan** [comment]
@Audelweiss I have separated this into another issue here - #46

**Comment by Nikschavan** [comment]
Moved the comments into issue #46

**Comment by Nikschavan** [comment]
Fixed with #177
