### ISSUE TITLE
Adding Meta description and keyword into header

### ISSUE THREAD

**Issue by benyapzl** [Nikschavan/header-footer-elementor#302]
Hi, i want to add meta description and keyword manually into the header file. i edited hfe_header in themes-> default->hfe_header.php.

However, when i refresh my website and view page source, i did not see my meta being added in.

**Comment by SuryawanshiPrajakta** [comment]
Hello @benyapzl,

Could you please provide me with some steps to check this on my end? This will help us in understanding what exactly you are trying to achieve and what is being missed during it.

Looking forward to hearing from you.

**Comment by SuryawanshiPrajakta** [comment]
Hey @benyapzl,

Greetings for the day!

I didn't hear back from you. Did you get it to work?

Looking forward to hearing from you.

**Comment by SuryawanshiPrajakta** [comment]
Hey @benyapzl,

I am closing this issue as I haven't heard back from us. I hope you have resolved the issue.

However, please do not hesitate to open a new issue or write here if you still need assistance with this.

Regards,
Prajakta Suryawanshi
