### ISSUE TITLE
Zakra Theme Mobile menu not working: Only Footer changed

### ISSUE THREAD

**Issue by Progressive-Programmer** [Nikschavan/header-footer-elementor#319]
### I should be able to use zakra theme mobile menu (toggle option) when I change just the footer for the theme.

**To reproduce the bug.** 
Install Zakra theme
Activate
Add Zakra theme import 
Choose Zakra Cafe Theme (Import - Activate)
Add Elementor Header Footer Plugin 
Add custom Footer (only) 

Check website in mobile mode. 
Click on the toggle mobile menu.  

the problem happens with no other plugin. Checked deactivating other plugins. 

_Wordpress Version 5.5
Elementor Version  v2.9.14_ 

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

**Comment by SuryawanshiPrajakta** [comment]
Hello @Progressive-Programmer,

Thank you for getting in touch with us!

I checked the issue at my end. This is only with the Method - 1 of Theme Support. This method supports most of the themes using some WordPress's default hooks. 

However, if this is not working well with your theme, then, please choose Method - 2 -- https://share.getcloudapp.com/YEuoW1gW. This method hides your theme's header & footer template with CSS and displays custom templates from the plugin.

I see that the menu issue is fixing after switching to Method -- 2 -- https://share.getcloudapp.com/p9uGQ7nY.

I hope this helps. Please let me know if you have any further queries.

Regards,
Prajakta
