### ISSUE TITLE
Since last update, Footer became broken

### ISSUE THREAD

**Issue by dvjrickkraft** [Nikschavan/header-footer-elementor#321]
Noticed a few changes about our Footer since we updated this plug-in and also Elementor.  On https://techspinreview.com

In Wordpress dashboard, Templates says "No Templates Found" though there is an 'All (1)' and Published, too.  The template was renamed from Footer to "Default Site", and three of the buttons now don't work. (YT, TW, FB)

![Ele HeadFoot bug2](https://user-images.githubusercontent.com/5501662/93558335-cf41a400-f9af-11ea-883c-5e94e37db614.PNG)

A larger issue is that I am no longer able to edit the template in Elementor, it's stuck on the 'Site Settings' and the back (left) arrow is grayed out, clicking the X dumps me back to Wordpress page edit.  The sections are not clickable/selectable.

![Ele HeadFoot bug](https://user-images.githubusercontent.com/5501662/93558030-1f6c3680-f9af-11ea-98e0-c6e81d3bc29b.PNG)

Using OceanWP with Elementor, and these plugins, Wordpress 5.5.1, Elementor 1.5.3
![Ele HeadFoot plugins](https://user-images.githubusercontent.com/5501662/93558772-c6050700-f9b0-11ea-8479-584ca928cedd.PNG)

Not a lot of time today to test, running out the door to my second job, just reporting this and will test more tonight.  Let me know if there's something I can do to help.  Cheers, Rick.

**Comment by egoizte** [comment]
Same issue - unable to edit hf templates. Elementor 3.0.7, Elementor Pro 3.0.4

**Comment by SuryawanshiPrajakta** [comment]
Hello @dvjrickkraft and @egoizte,

Apologies for the delay in response!

I had a look into this issue, but I was unable to reproduce it at my end using EHF - 1.5.3, Elementor 3.0.9, WordPress - 5.5.1. Please refer to this video -- https://share.getcloudapp.com/8LuPX8Qz.

Could you please check if flushing the permalinks help? -- https://wpastra.com/docs/how-to-refresh-wordpress-permalinks/.

Also, just to let you know, Elementor - Header, Footer, and Blocks templates gets listed under Appearence -> Header, Footer and Blocks -- https://share.getcloudapp.com/YEuoLxAW.

If this information doesn't help, please deactivate all plugins temporarily and see if that solves the problem. Then, activate plugins one by one to see which plugin is causing the problem.

Looking forward to hearing from you.

Regards,
Prajakta

**Comment by egoizte** [comment]
Thanks, Prajakta! Permalinks flush helped.

**Comment by dvjrickkraft** [comment]
Not sure why but after I deleted the extra 'Template' and updated, and then deleted/recreated a footer under Appearence -> Header, Footer and Blocks, everything is working... actually, better than before haha.  Thanks for your reply!  Nice job on the plugin by the way!

**Comment by SuryawanshiPrajakta** [comment]
Hello,

I am glad that the issue is resolved!

Please do not hesitate to get back to us if you need assistance with anything else.

Have a great day ahead!

Regards,
Prajakta
