### ISSUE TITLE
Add Theme Support not affecting the unsupported theme nag

### ISSUE THREAD

**Issue by norewp** [Nikschavan/header-footer-elementor#33]
I've added support for upcoming theme and both header & footer function as they should.

The only probplem I'm facing is that the unsupported theme nag still shows after adding `add_theme_support( 'header-footer-elementor' );` - any ideas on how to remedie this?

**Comment by Nikschavan** [comment]
Can you try the PR #34 I just pushed for this change?

Basically, the plugin should wait until `after_setup_theme`for theme's to declare the support.

**Comment by norewp** [comment]
That does the trick, thank you :)

**Comment by Nikschavan** [comment]
Hello @norewp,

I just released an update with this fix :)
