### ISSUE TITLE
Header and Footer blank

### ISSUE THREAD

**Issue by bbschnapp** [Nikschavan/header-footer-elementor#35]
Hello,
Thanks for creating this plugin!

I do have an issue, where the header and footer are in place, as they cover the theme header and footer (astra) – but show up as blank. For ref. the site is hansburkhardtestate.com

Is this a cache issue? I have tried to delete and re-install the plugin both via WP admin and via FTP. I have also deleted my headers and made new ones, without luck.

Thanks.

**Comment by Nikschavan** [comment]
Hello @bbschnapp,

You seem to have a JavaScript error in the developer console coming from Navmenu Plugin, Can you try disabling that plugin and see if the issue is fixed?

**Comment by bbschnapp** [comment]
Thanks,
I deleted that one, and deactivated, deleted and re-installed Header/Footer without luck.

**Comment by bbschnapp** [comment]
The Plugin 'Page Templater For Elementor' was causing the issue. Thanks for pointing me in the right direction. Upon deleting that one, the header is visible.
