### ISSUE TITLE
Plugin cause duplicate content render

### ISSUE THREAD

**Issue by itay9001** [Nikschavan/header-footer-elementor#37]
This plugin seem to cause duplicate rendering of the page content, which can cause a memory issue, and a problem when using "require\include once" inside the content.

Seem to happen because of creating new instance of "Frontend" class instead of inherit the frontend from the Elementor class.

PL a fix.

**Comment by Nikschavan** [comment]
Thank you for this @itay9001,

Merged the PR #36
