### ISSUE TITLE
FYI: Link in details dialogue is wrong

### ISSUE THREAD

**Issue by xtramuse** [Nikschavan/header-footer-elementor#38]
https://github.com/Nikschavan/header-footer-elemento 

It's missing the r

**Comment by Nikschavan** [comment]
Hello @xtramuse,

Thank you for reporting, although this was already fixed in a commit 02d839564cc8e54bd9bd1cacac88c1ad6096e5a8. This version is already updated on [W.org](W.org)

Can you give a screenshot of where is this broken link added?

**Comment by xtramuse** [comment]
![2017-09-20_12-27-52](https://user-images.githubusercontent.com/19857457/30639970-5da8616a-9e01-11e7-938f-abe6b38c65a5.png)

**Comment by Nikschavan** [comment]
Thank you for reporting @xtramuse. I just pushed the PR #39 that will update this URL
