### ISSUE TITLE
Disable custom header on _underscores theme

### ISSUE THREAD

**Issue by eyalbin** [Nikschavan/header-footer-elementor#40]
Hi,

I am using _underscores theme, which is a very solid, lightweight, basic theme which is using the default wordpress custom header for header.

I didn't figure out how to disable this basic custom header with this function that is described in the wiki:

```
remove_action( 'astra_header', 'astra_header_markup' );
function your_prefix_render_hfe_header() {
	
	if ( function_exists( 'hfe_render_header' ) ) {
		hfe_render_header();
	}

}

add_action( 'astra_header', 'your_prefix_render_hfe_header' );
```
I just didn't find the header action anywhere... your help will be very appreciated.

**Comment by Nikschavan** [comment]
Hello @eyalbin,

_S does not have all the actions and filters built in, in this case you can follow this tutorial for adding the theme support yourself - https://github.com/Nikschavan/header-footer-elementor/wiki/Add-support-to-your-theme-by-yourself


Let me know if there is any confusion in the tutorial I will try to improve it.
