### ISSUE TITLE
Site crash

### ISSUE THREAD

**Issue by kyrp2c** [Nikschavan/header-footer-elementor#42]
I just installed the plugin and now my wordpress site has crashed. i cannot access my account ot my website and the following pops up:

Fatal error: Class 'Elementor\Plugin' not found in /public/sites/www.iphonereparatie.amsterdam/wp-content/plugins/header-footer-elementor/inc/class-header-footer-elementor.php on line 35

**Comment by Nikschavan** [comment]
Hey @kyrp2c,

This is because this plugin requires elementor activated and it seems you have lower version of PHP which is not allowing elementor to be activated.

Can you upgrade your PHP version by contacting your web host?

**Comment by Nikschavan** [comment]
To disable the header-footer plugin you will have to rename the folder of this plugin by logging in to FTP of your website.

**Comment by kyrp2c** [comment]
But I am unable to access my website at all, so how can I do this?

**Comment by Nikschavan** [comment]
You won't need to access your website to access this. You will need to access the web hosting panel of your website. This is where all the files for your website are stored.
You can contact your web host for this details if you don't have them.

**Comment by kyrp2c** [comment]
I have found the header footer elementor map in my FTP but I cannot rename the map. Its a read only map so I cannot make changes. So what should I do, because it is unclear to me what I have to do.

**Comment by kyrp2c** [comment]
![whatsapp image 2017-10-24 at 17 08 35](https://user-images.githubusercontent.com/33061588/31951778-465c0a86-b8df-11e7-99fe-de7eb18fe21c.jpeg)

**Comment by Nikschavan** [comment]
Can you rename the folder `header-footer-elementor` to something else or simply delete it? That will deactivate the plugin.

**Comment by kyrp2c** [comment]
No unfortunately that is not an option. I can only duplicate the map or file. 

Is there another option?

**Comment by Nikschavan** [comment]
do you have any other access level on the server like cpanel? your hosting provider should be able to delete this folder for you.

**Comment by Nikschavan** [comment]
1. Download this file - https://cl.ly/nHKq
2. In your `wp-content/` directory create a folder `mu-plugins` and upload this file to that folder
3. Reload your website and the plugin should work.

This will deactivate the plugin `header-footer-elementor` on your site.

**Comment by Nikschavan** [comment]
@kyrp2c,

Your site seems to be working now, I have updated the plugin on W.org so that this does not happen once again. Although, you will still need PHP5.4 or higher in order for Elementor to work.

**Comment by kyrp2c** [comment]
@Nikschavan It has been fixed, thanks!
