### ISSUE TITLE
Plugin not working on multisite and Astra

### ISSUE THREAD

**Issue by Nikschavan** [Nikschavan/header-footer-elementor#46]
Copied from @Audelweiss comment from -  https://github.com/Nikschavan/header-footer-elementor/issues/29#issuecomment-341118027

Hello, I'm trying to use this plugin on my WP multisite with Astra theme but I have the following error message

![capture](https://user-images.githubusercontent.com/17007867/32278868-5593fb9c-bf17-11e7-92d5-4882dfd40f24.PNG)

**Comment by Nikschavan** [comment]
Hello @Audelweiss

It seems to be working for me when I am trying on a multisite with Astra and the Astra Child theme - https://cl.ly/nRRl

Can you check what is the name of the folder of your Astra main theme?

**Comment by Audelweiss** [comment]
The name of the folder is "astra"

**Comment by Nikschavan** [comment]
This is weird, Astra is definitely supported. This seems to be some weird issue. Can you open up a support from this form - https://wpastra.com/support/
Also, can you share credentials to your site from here? I will check what exactly is the problem here.

**Comment by Audelweiss** [comment]
"Also, can you share credentials to your site from here?" 
Sorry I'm french and I don't understand what does that mean... You want the URL of the website ?

**Comment by Nikschavan** [comment]
You are right.

**Comment by Audelweiss** [comment]
https://modele1.blog.audreyhossepian.fr/
I disabled the plugin since

**Comment by Nikschavan** [comment]
The name of the folder seems to be `Astra` on your site (https://cl.ly/nVXJ). If you install the theme from W.org it will create the folder to be `astra`.

The name of the folder is actually the slug of the theme and that might be the reason the plugin is not able to identify this as a supported theme. Can you rename the folder to `astra` - all small letters and see if that is working?

**Comment by Audelweiss** [comment]
It works fine now !

**Comment by Nikschavan** [comment]
Glad it has been fixed @Audelweiss.
