### ISSUE TITLE
Front Page

### ISSUE THREAD

**Issue by garciacrew** [Nikschavan/header-footer-elementor#47]
Is there a way to hide the header/footer on the Front Page?  I cannot even get it to hide when I use an Elementor canvas template for a page.  It would be nice if there was an elementor canvas and an elementor canvas - hfe page template option.

**Comment by Nikschavan** [comment]
This plugin does not work when Elementor canvas is used. So if you are using Elementor canvas the header for from hfe will not be displayed.

**Comment by garciacrew** [comment]
It Is ignoring the elementor canvas. tried all but Genesis themes too. I literally just figured out one way to disable it and it is by removing the action in the elementor canvas template.

Do you have any diagnostic tips?  I prefer to not have to hack the elementor plugin in case they update it. I'd have to remember to go back and fix it again.

By the way. Thanks for the quick reply.


Sent from my iPhone.
_____________________________

**Comment by SelinaSMG** [comment]
Hi,

I am having a similar issue the header is not displaying on my front page or any page for that matter. I have set it up exactly how it was explained on the set up for the plugin. The plugin is activate. Please can you explain why the header is not being displayed?

**Comment by garciacrew** [comment]
You can try this to see if it will just show up.  It worked for me and then I just had to add additional code to keep the header from showing.

`/*
 *
 * Add header footer elementor functions
 *
 */
function wid_render_hfe_header() {
    
    if ( function_exists( 'hfe_render_header' ) ) {
        hfe_render_header();
    }

}

function wid_render_hfe_footer() {
    
    if ( function_exists( 'hfe_render_footer' ) ) {
        hfe_render_footer();
    }

}

add_action( 'wp_head', 'wid_render_hfe_header' );
add_action( 'wp_footer', 'wid_render_hfe_footer' );


/*
 *
 * Reflect the theme support for the header footer elementor plugin
 *
 */
function wid_header_footer_elementor_support() {
    add_theme_support( 'header-footer-elementor' );
}


add_action( 'after_setup_theme', 'wid_header_footer_elementor_support' );
`

 I did this in my child theme header.  I kept everything so the head was still loading and such, but conditioned if the HFE function was not present then it showed the normal header for the theme.  If it was then it would now show the header.  This kept two headers from showing on my page(s).

`<?php if ( !function_exists( 'hfe_render_header' ) ) : ?>`

**Comment by SelinaSMG** [comment]
@garciacrew 

Thank you for your response, much appreciated.

I am not competent in coding and I want to ensure your above coding enables my customised Header I made in the Plugin Header & footer shows up on all my pages. At present no header is showing not even my Generate press theme header.

Please can you confirm that this coding will enable my customised Header made in the plugin to show up in the home page and all other pages on my website.

I look forward to your response.

Selina

**Comment by garciacrew** [comment]
@SelinaSMG I don't have enough information to make that kind of statement.  The code I provided was what I have implemented in my custom theme to enable the Header Footer Elementor plugin with the theme and register it so I don't get the alert in the admin area that my theme is not compatible with the Header Footer Elementor plugin.

Although, if your header/footer are not showing up at all, you might have another issue.  It could also be as simple as - did include the code above or what was provided in the support page for the plugin?  If so, did you enable the plugin?  If so, did you create a header and a footer file for the plugin to use?

**Comment by Nikschavan** [comment]
@SelinaSMG 

> At present no header is showing not even my Generate press theme header.

If the theme's header is not being displayed the header from this plugin will also not work. This is because this plugin just replaces the header added by the theme. Can you check if you are using the elementor canvas template on the page in question?

@garciacrew To diagnose - You can first install plugin `query-monitor` and check for the `Template`s that are loaded. This is how it is looking for me when using an elementor canvas template (https://cl.ly/nYzs) notice it does not call for the header.php template hence the header does not ideally render in that case. I am guessing header should be called in your case.
My guess is that this is coming from some of the child theme customizations.

**Comment by SelinaSMG** [comment]
@Nikschavan yes I am using the Elementor canvas for my all pages on my website including the Header I created in the Header footer plugin. 

Please find a picture of query monitor and 3 pictures to showing the back office of my homepage. Please play attention to the information on the side bar and inform me if the right section are accurately ticked.
![img_1401](https://user-images.githubusercontent.com/33391853/32491661-6afc7198-c3af-11e7-8bff-8a4102bd7b75.PNG)
![img_1402](https://user-images.githubusercontent.com/33391853/32491662-6b1c509e-c3af-11e7-8d0c-038f5ba6c6b9.PNG)
![img_1403](https://user-images.githubusercontent.com/33391853/32491663-6b39bf3a-c3af-11e7-9076-0cd7187568b7.PNG)
![img_1404](https://user-images.githubusercontent.com/33391853/32491665-6b604bdc-c3af-11e7-87f9-d5125ff3c30e.PNG)

Many thanks,  

Selina

**Comment by Nikschavan** [comment]
Hey @garciacrew, @SelinaSMG

The latest version of the plugin adds an option force use the header / footer templates on pages using Elementor Canvas template. This should your problem.

**Comment by SelinaSMG** [comment]
Thank you you for your assistance.

My header issue is fully resolved. I needed to tick the No navigation bar
under customisation  in generate press.
