### ISSUE TITLE
On page load, the header blows up to 2x size, then back to normal

### ISSUE THREAD

**Issue by MarkInPA** [Nikschavan/header-footer-elementor#49]
Using your plugin, with Elementor Pro and Astra Theme. 

Please see the problem when you visit my website, [www.dailyinchrist.org](http://www.dailyinchrist.org)

On page load, the header blows up to full image size for the header height, before going to normal height in 1 or 2 seconds. This is happening on desktop, mobile & tablet.

Looks like a bug.

Thanks,
Mark

**Comment by Nikschavan** [comment]
Hey @MarkInPA are you using the latest version of the plugin? This _ideally_ should not be happening the plugin loads the CSS stylesheets in `<head>`

**Comment by MarkInPA** [comment]
Now I upgraded to Version 1.0.7. I know I've upgraded to another upgrade since this original post. The problem is mostly gone now. Just more of a flash of the larger header image for a fraction of a second. that's acceptable. Thanks!
