### ISSUE TITLE
Can you add support to add/remove the Header and Footer on individual pages?

### ISSUE THREAD

**Issue by luckybandit** [Nikschavan/header-footer-elementor#58]
Could I request that you add an option so we can choose on individual pages which headers and footers we would like to use for that page? 

If possible, at least allow the option to disable Header/Footer for certain pages? 

Currently there are some pages such as Home Hero Images or things that:

1) Do not need a footer or header
2) Require different headers because of transparency issues for transparent headers. 

This would help tremendously as Astra also does not allow this option. GeneratePress allows for changing of header/footer but only on the theme. Cannot use Elementor as a builder for the header/footer which would be infinitely flexible. 

Without this change it makes all of the new, nice elementor nav options kind of pointless unless you have consistent header/footer for each page. 

Thanks

**Comment by AndyFarout** [comment]
Same here. The only choice here seems to deactivate it. Which seems counterproductive.

**Comment by kkri** [comment]
Hi. The individual page header/footer choice would be awesome considering that using Elementor would be possible to add widgets too, so that it would be much more useful for Xmas effects, ads and so on, Could you tell us if you're near to realize it or not? Thank you very much for your work.

**Comment by Nikschavan** [comment]
Hey @kkri, @AndyFarout, @luckybandit 

I will be adding this feature in one of the future updates. As of now this is available as a part of [Astra Pro](https://wpastra.com/) addon for the Astra Theme. 

Related (#29)
