### ISSUE TITLE
Admin Menu placement.

### ISSUE THREAD

**Issue by WPDevHQ** [Nikschavan/header-footer-elementor#6]
As this is a Design functionality plugin then the menu for the CPT is more apripriately suited to be under the Appearance tab.

Where it is right now implies that this is a settings functionality for WordPress!

**Comment by Nikschavan** [comment]
Thank you for the suggestion @WPDevHQ, You are right about the menu placement. the appropriate place for the menu would be under appearance.

**Comment by WPDevHQ** [comment]
I'd actually call the menu link Header Footer Builder
![headerfooterbuilder](https://cloud.githubusercontent.com/assets/16872407/24209986/91e54bd0-0f1f-11e7-9f1c-eb3685dd5f34.png)

**Comment by Nikschavan** [comment]
Right, Header Footer Builder is much more simpler and relevant.
