### ISSUE TITLE
Does not support 

### ISSUE THREAD

**Issue by fahadmehar** [Nikschavan/header-footer-elementor#62]
I am using THEME Theme: Merriment by Benjamin Lu. It does not support.  Need Help here

**Comment by Nikschavan** [comment]
Hello,

You can ask contact the theme author and point them to this wiki article so that they can add support for this plugin very easily - https://github.com/Nikschavan/header-footer-elementor/wiki/Add-support-to-Header-Footer-Elementor-from-the-Child-Theme
