### ISSUE TITLE
Elementor nav dropdown behind Astra page title

### ISSUE THREAD

**Issue by MrBlank** [Nikschavan/header-footer-elementor#63]
With the Astra theme, when I make a header in Elementor and use the navigation widget, the mobile dropdown goes behind the default theme page title. (See screenshots)

.ehf-header header {
  z-index: auto;
}
This seems to fix it, but why does the page header need a z-index set?

In your css: 

/* Fix: Header hidden below the page content */
.ehf-header header {
    z-index: 30;
    position: relative;
}

<img width="797" alt="screen shot 2017-12-20 at 10 49 54 am" src="https://user-images.githubusercontent.com/51711/34218612-460dd3e0-e574-11e7-931a-cb3b800d9af2.png">
<img width="796" alt="screen shot 2017-12-20 at 10 50 05 am" src="https://user-images.githubusercontent.com/51711/34218613-461f29c4-e574-11e7-9ebc-e5d56774ae53.png">

**Comment by Nikschavan** [comment]
Hello,

Are you still facing this problem? I just checked and could not reproduce this issue - https://cl.ly/p2T8

**Comment by MrBlank** [comment]
I can't reproduce either. Maybe Elementor had an update to the Menu widget styles? Seems like it isn't a problem anymore. Thanks for looking into it.

**Comment by chucknorris88** [comment]
Hi, sorry to hijack and bring up such an old thread. I've been trying to figure out this issue for almost 4 hours. I'm experiencing this same issue currently and the issue isn't resolving itself. Both issues are in the elementor header running off Astra as well. The drop down menu is suddenly hidden behind the content (see image). ALSO, there is always this white bar  visible when I have set the menu to be a transparent background.  My goal is to get the drop down menu appearing in the front of the stack again as well as use a sticky header that appears black with a opposite colored logo upon scroll.
<img width="1440" alt="Screen Shot 2019-04-11 at 12 07 00 PM" src="https://user-images.githubusercontent.com/49534635/55985015-a6ae6a00-5c53-11e9-839b-08a86e989d83.png">

**Comment by Cecilia941** [comment]
I am having the same issue with Elementor and Astra theme.  I've used Elementor Nav menu many times and have never seen this problem.  Did anyone find a solution to this?

**Comment by Nikschavan** [comment]
@Cecilia941 / @chucknorris88 - do you have a domain where I can check the error that you are facing?

**Comment by Cecilia941** [comment]
http://hammondl.nw69.fcomet.com/wp/

I changed the Nav Menu z-index to 999 and made some of the content z-index: 5 and still no luck.

thanks for your help.

**Comment by Nikschavan** [comment]
looks like this plugin is not installed on your site. You will need to contact the Elementor support team as you are using Elementor Pro on your site - https://elementor.com/support/

**Comment by Cecilia941** [comment]
OK.  Thanks.  just submitted a ticket.
