### ISSUE TITLE
Plugin not working in Elementor Template

### ISSUE THREAD

**Issue by grayowl** [Nikschavan/header-footer-elementor#64]
Hi

I am using OceanWP & Elementor in the Elementor Template mode. Went to use your plugin and I got this: 'Your theme must declare the "add_theme_support( 'custom-logo')" for the logo to work' when tried to use Branding mode - Logo.

Does this plugin only work in a WP Template, like OceanWP and nothing else.

The site is www.pal4paws.co.uk/test - also have attached screen shot of message.

Would like workround or your comments.

Regards
Lee

![screen shot 2018-01-02 at 07 54 21](https://user-images.githubusercontent.com/6575745/34477458-47127d2c-ef92-11e7-84e7-9837e175f689.png)

**Comment by Nikschavan** [comment]
Hello @grayowl,

This plugin just provides a post type where you can design the header and footer using elementor page builder. This plugin does not add anything specific to the theme/elementor.

The problem you are facing is between some compatibility from the addon that is allowing to add the logo and your theme. Your theme author should be able to fix this problem.
