### ISSUE TITLE
Editing the drop-down menu icon and page active states?

### ISSUE THREAD

**Issue by SyCramp** [Nikschavan/header-footer-elementor#66]
Hi, 

I love the plugin, it's brilliant but I'm having some issues editing drop-down menu icons and active state preferences. I've looked at the elementor pro dashboard over and over but I cannot seem to find how I edit them! I've written more details below, fingers crossed you can help! I'm using Elemnetor Pro with GeneratePress (free).

1. How can I change the drop-down menu icon? It's currently a down arrow and it doesn't align with the side of the text/button, it drops below it, even when the horizontal spacing is increased. See screenshot 1. 

<img width="722" alt="screen shot 1" src="https://user-images.githubusercontent.com/35382989/34895150-549968fa-f7dc-11e7-9a5a-83a5fe882370.png">

2. How do I change the active state? It currently changes the text to bold. Again screenshot attached.

<img width="758" alt="screen shot 2" src="https://user-images.githubusercontent.com/35382989/34895182-6d4b3cc0-f7dc-11e7-8c7c-cc4901edba48.png">

I hope you can help, thank you! 

Sy

**Comment by Nikschavan** [comment]
Hello @SyCramp,

This plugin just provides a post type where you create a header layout using [Elementor Page Builder](https://elementor.com/). This plugin does not add any widgets to elementor or any other customizations. So it is recommended to contact the Elementor's support channel for this issue - https://wordpress.org/plugins/elementor/
