### ISSUE TITLE
Conflict with Press Elements

### ISSUE THREAD

**Issue by WPDevHQ** [Nikschavan/header-footer-elementor#7]
There seems to be a conflict with Press Elements in the Editor. https://wordpress.org/plugins/press-elements/

This plugin takes over and modifies the modules from Press Elements i.e "Post Title" gets changed to "Elementor Header Footer Title"

Is this the inteded behaviour?

Does the plugin comes with its own modules to build out the header or does it rely on 3rd party elements?

**Comment by Nikschavan** [comment]
I checked the code from Press Element's Post Title Widget, The name of the Title Widget they have is "<post-type> Title" So when editing a page it says 'Page title' and when editing a post it says 'Post title'. So Similarly When editing header footer CPT it says 'Elementor Header Footer Title', It seems Press Elements wants it to be this way.

About custom widgets, Currently the plugin does not come with its own modules but I will bring new modules which are essential for creating the headers and footers in near future.

**Comment by WPDevHQ** [comment]
OK, if that's their intent then it makes sense. They probably should note that so it doesn't confuse users.

Closing this a non issue in that case.
