### ISSUE TITLE
Header html code inside <head></head> tag

### ISSUE THREAD

**Issue by emilsan** [Nikschavan/header-footer-elementor#75]
this plugin push it's `<header>` html code inside `<head>` instead of `<body>`

**Comment by Nikschavan** [comment]
Hello @emilsan,

Are you using the Elementor Canvas template for the page where this is happening?

**Comment by emilsan** [comment]
Yes.

**Comment by Nikschavan** [comment]
Can you share the URL of your page? I cannot reproduce this my test site. Here is the screenshot - https://cl.ly/pD9y

**Comment by emilsan** [comment]
I'm using ASTRA theme . Tested on OceanWP also. Same bug
If i change to "Default template", there is no issue.

Please do view source page instead of developer view.


[image: Inline image 1]



[image: Inline image 2]

**Comment by Nikschavan** [comment]
@emilsan I just pushed the change in the PR #79.

Will you be able to test this and verify that this fixes the problem?

**Comment by emilsan** [comment]
Problem fixed. Thank you!
