### ISSUE TITLE
My header works but my footer isn't working.

### ISSUE THREAD

**Issue by joychiaoyin** [Nikschavan/header-footer-elementor#76]
Hi My header works pretty well in every pages but footer doesn't work. I don't know why.

**Comment by Nikschavan** [comment]
Hello @joychiaoyin,

Can you give a link of the page where I can see the error?

**Comment by Nikschavan** [comment]
Hello @joychiaoyin,

Can you open up a support ticket at - https://wpastra.com/support/ if you are still facing this problem?

**Comment by joychiaoyin** [comment]
Hi,
Sorry for late reply. I solved the problems. I just deleted a code
accidentally.
Thanks a lot!
Best,
Joy
