### ISSUE TITLE
Footer not showin on blogposts anymore

### ISSUE THREAD

**Issue by tilecuwi** [Nikschavan/header-footer-elementor#80]
Hi, since the update today, the footer is not showing on Blogposts anymore. 
It was showing perfectly before the update.

**Comment by Nikschavan** [comment]
Hello @tilecuwi,

Can you give a link where this is happening so that I can check this real quick?

**Comment by Nikschavan** [comment]
What theme are you using? also, are you possibly using the Elementor Canvas template for the Posts?

**Comment by tilecuwi** [comment]
Hi, yes i am using the elementor canvas for all my posts. My theme is GeneratePress Premium.
Homepage: https://www.abnehmhero.de
Blogpost: https://www.abnehmhero.de/12-geniale-ideen-fuer-einen-energievollen-morgen/

**Comment by Nikschavan** [comment]
I tried using this on GP with Elementor Canvas template but this seems to be working for me, Can you give some more information about how the footer is configured on posts?

What is the version of the Elementor/Elementor Pro are you using?

**Comment by tilecuwi** [comment]
I am using Elementor Standard Version. 
On Posts Footer Widget is set as "Standard", but i also tried "0 widgets".

**Comment by Nikschavan** [comment]
For some reason, I am not able to reproduce this on my site. I am guessing this is conflict with some other plugin on your site.

Could you please open up a support ticket by filling up this contact form so that we can debug this quicker? - https://wpastra.com/support/
