### ISSUE TITLE
Stacked Columns 

### ISSUE THREAD

**Issue by murph019** [Nikschavan/header-footer-elementor#82]
Hi,

I'd like to stack columns in a Header, essentially to have social icons above various other buttons, but can't seem to work out how to do this.

Any advice?

Thanks

**Comment by Nikschavan** [comment]
This is something that can be done from Elementor’s settings.

Elementor allows you to set column widths for responsive devices. You just need to add correct widths that you want on tablet and mobile – https://cl.ly/pj7G

For more information on this you can ask the guys at Elementor – https://wordpress.org/support/plugin/elementor
