### ISSUE TITLE
Sub-menu behind content 

### ISSUE THREAD

**Issue by ReneePaule** [Nikschavan/header-footer-elementor#83]
I made a header with header-footer-elementor. It's great, but on my blog page when I hover over 'books' if the mouse is on the left hand side of the sub menu it can't select anything on several of the links as text on the page is getting in the way. This is the url www.reneepaule.com/blog

Any suggestions?

**Comment by Nikschavan** [comment]
The CSS selector needs to target only the `<header id="mastthead">` Right now it is targeting all `<header>` tags which also appear in the post.

Change is required here - https://github.com/Nikschavan/header-footer-elementor/blob/master/assets/css/header-footer-elementor.css#L30

`.ehf-header header`

**Comment by Xusje** [comment]
Is there also a version to fix this for the footer? Because my sticky content scrolls over my footer when I scroll down, and I don't like that.
