### ISSUE TITLE
Unable to Display Preview

### ISSUE THREAD

**Issue by jeffnissen** [Nikschavan/header-footer-elementor#84]
I'm unable to bring up the Elementor Preview to create a Header or Footer. It seems to be isolated to the this plugin as I can bring up the Preview in page layouts.

I've deactivated plugins, switched out themes, tried changing permalink names, but nothing resolves the issue. 

<img width="1409" alt="screen shot 2018-02-18 at 10 36 34 am" src="https://user-images.githubusercontent.com/7025227/36355425-d07bde8a-1497-11e8-9bba-248864a68822.png">

**Comment by Nikschavan** [comment]
Hello @jeffnissen,

Can you disable Elementor on the page and just open the URL and see if the page can be displayed correctly? Also, Can you [enable logging](https://codex.wordpress.org/Debugging_in_WordPress) to see if you have any errors.

Also, Can you open up a support ticket at - https://wpastra.com/support/ as GitHub is mostly used for development related tasks?
