### ISSUE TITLE
BlankSlate-HFE site is down (showing maintenance mode) after upgrading

### ISSUE THREAD

**Issue by bendqh** [Nikschavan/header-footer-elementor#89]
I use Ubuntu 16.04 with Nginx and I have a WordPress site with the theme "BlankSlate". I have only these plugins activated:

Elementor
Header Footer Elementor (HFE)
CF7
Call now button.

The site is very small: All default, up to about 10 pages up to about 10 images.

---

After upgrading anything this way (after a month and a half without upgrade) this way:

	wp plugin update --all --allow-root
	wp core update --allow-root
	wp language core update --allow-root
	wp theme update --all --allow-root

all pages of my site response with "maintenance mode" although I didn't put my site in maintenance mode.

I thought this might happen because of BlankSlate-HFE discrepancy so I tried to change theme from BlanksSlate to GeneratePress with WP-CLI and flush cache:

    wp theme install generatepress --activate --allow-root
    wp flush-cache allow-root

I then went to `functions.php` and removed all old HFE-BlankSlate code and the site worked but I don't want to use GeneratePress as it gives me bad Google Pagespeed Insights score in comparison to BlankSlate.

Will you agree to add BlankSlate support?

**Comment by benqzq** [comment]
Well, actually, never mind for me. I started using Astra which is best supported  by you (your theme Nikhil?). As I understand and as I feel (😄 )  it's ultra lightweight, more than another theme you support (😆 ), comfortable to use, neat, and beautiful ! I assume that from now and long I'll likely to use Astra as well for other projects in similar scale of plugins and pages.

Thanks,

**Comment by Nikschavan** [comment]
Glad that you liked the theme @bendqh :)

Do contact the [support of Astra](https://wpastra.com/support/) if you face any issues :)
