### ISSUE TITLE
Discrepancy between HFE and Astra wrapper widths

### ISSUE THREAD

**Issue by bendqh** [Nikschavan/header-footer-elementor#90]
I use latest Astra and HFE. After changing theme from BlankSlate to Astra I found this tiny problem:

![x](https://user-images.githubusercontent.com/31392185/37078709-0166b98a-21e9-11e8-891b-47d3d87a7584.PNG)

Note the width discrepancy between the two wrappers (Astra and HFE).

I could fix either by changing Astra wrapper to 1140px or manual CSS intervention though I'm not sure both of these actions are needed or logical. 

What do you think? Thanks.

**Comment by Nikschavan** [comment]
Hello @bendqh Can you open up a support ticket from the support form? - https://wpastra.com/support/submit-a-ticket/

**Comment by bendqh** [comment]
Sure dear Nik ! I posted there.
