### ISSUE TITLE
Footer won't stay at the bottom of webpage

### ISSUE THREAD

**Issue by ruben-leite** [Nikschavan/header-footer-elementor#92]
Greetings!

The footer for the single-page scrolling website I'm developing won't stay down at the bottom, which is fine for the main page, but it's pretty troubling when accessing blog posts that have little content, whereas in that case it stays floating in the middle of the screen. All I could think of was the following:

.footer {
position:absolute;
width:100%;
bottom:0;
}

but all that does is making the footer stay at the bottom limit of the browser's screen, which stays in the same place when I scroll down throughtout the main page of the website. What can I do in that case?

Thanks in advance!

Without the code above:
![ugh3](https://user-images.githubusercontent.com/37189543/37167876-040cc040-22fb-11e8-8a4f-c281a393f8f5.png)

With the code above:
![ugh2](https://user-images.githubusercontent.com/37189543/37167874-02ff40ec-22fb-11e8-87ea-0ffbbf84aca2.png)
![ugh1](https://user-images.githubusercontent.com/37189543/37167867-010ea296-22fb-11e8-8b38-8235b1a52078.png)

**Comment by Nikschavan** [comment]
Hello @ruben-leite 

Can you open up a support ticket from the support form? - https://wpastra.com/support/submit-a-ticket/
