### ISSUE TITLE
Header Footer-Plugin won't load with Elementor 2.0 Beta - 2

### ISSUE THREAD

**Issue by michelleist** [Nikschavan/header-footer-elementor#93]
Header Footer-Plugin won't load with Elementor 2.0 Beta - 2

Hoping for a fix soon :)

**Comment by Nikschavan** [comment]
Looks like Elementor 2.0 changes the location of the canvas template which this plugin loads when the header is being created. For now, I have corrected the location of the new template.
I will explore on how this plugin can better support the Elementor 2.0.
