### ISSUE TITLE
Footer not showing, but header does. 

### ISSUE THREAD

**Issue by jaymelyn525** [Nikschavan/header-footer-elementor#96]
I'm having a major issue with the footer not showing up. The header works just fine and I'm doing everything the way I always have. 
Theme: Astra

Please help ASAP as my deadline is being affected by this.

**Comment by jaymelyn525** [comment]
Please? Someone? Anyone?

**Comment by Nikschavan** [comment]
Can you give me a URL of the page where this is happening? Also which theme are you using?

**Comment by Nikschavan** [comment]
@jaymelyn525 Can you open up a support ticket from the support form? - https://wpastra.com/support/submit-a-ticket/
